---
cluster_groups:
- wheel
- gaussian
- bpa

cluster_users:
  - uid: wpatt2
    groups:
      - wheel
      - gaussian


enabled_repos:
- CentOS-Base.repo
- epel.repo

head_node_packages:
- tmux
- yum-plugin-downloadonly

all_node_rpms:
- htop
