---
- name: ensure groups are created
  group: name={{ item }} state=present
  with_items: cluster_groups
  sudo: yes

- name: Look up UIDs from ldapsearch
  shell: "ldapsearch -x uid={{ item.uid }} uidnumber gecos | egrep '^(uidnumber|gecos): ' | awk -F': ' '{print $2}'"
  with_items: cluster_users
  register: user_info
  always_run: yes
  changed_when: "user_info.rc != 0"
  # Fail if no ldap results are found
  failed_when: "user_info.stdout_lines == []"

- name: Ensure user accounts are created
  user: name={{ item.item.uid }}
    uid="{{ item.stdout_lines[0] }}"
    comment="{{ item.stdout_lines[1] }}"
    groups="{{ item.item.groups| default([]) | join(',') or omit }}"
  with_items: user_info.results
  sudo: yes

- name: Get User System-Wide Groups
  shell: ldapsearch -x memberUid={{item.uid}} | grep " Group," | awk -F "\"*,\"*" '{print $1}' | awk '{ gsub ("# ", "", $0); print}'
  register: "user_ldap_groups"
  with_items: cluster_users
  always_run: yes
  changed_when: "user_ldap_groups.rc != 0"
  failed_when: "user_ldap_groups.stdout_lines == []"

- name: Get UIDs
  shell: "ldapsearch -x memberUid={{item.0.item.uid}} | tr '\n' '\t' | grep -oP 'cn={{item.1}}.*?gidNumber: [0-9]*' | tr '\t' '\n' | grep gidNumber | awk -F ' ' '{print $2}'"
  register: "gids"
  with_subelements:
    - "{{user_ldap_groups.results}}"
    - stdout_lines

- debug: var=item.item.1
  with_items: "{{gids.results}}"

- name: Create All Research Groups
  group: name={{ item.item.1 }} state=present gid={{ item.stdout }}
  when: "'resgrp' in '{{ item.item.1}}'"
  with_items: "{{gids.results}}"
  sudo: yes


#- name: Create All Research Groups
#  group: name={{ item.1 }} state=present
#  when: "'resgrp' in '{{ item.1 }}'"
#  with_subelements: 
#    - "{{user_ldap_groups.results}}"
#    - stdout_lines
#  sudo: yes

- name: Add Users to research Groups
  user: name={{ item.0.item.uid }}
      group={{ item.0.item.uid }}
      groups={{ item.1 }}
      append=yes
  when: "'resgrp' in '{{ item.1 }}'"
  with_subelements: 
    - "{{user_ldap_groups.results}}"
    - stdout_lines
  sudo: yes
  notify: sync users


